name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: mpa-forge/.github/.github/workflows/reusable-ci-go.yml@main
    secrets: inherit
    with:
      working-directory: "."
      sonar-organization-key: ""
      sonar-project-key: ""
